In [1]:
def add(*n):
    s = 0 
    for i in n :
        s += i # s = s + i 
    return s 

In [4]:
add(3+12)

15

In [5]:
def check(num):
    if num % 2 == 0 :
        return "Even"
    else:
        return "Odd"

In [6]:
check(3)

'Odd'

In [7]:
check(4)

'Even'

In [8]:
def Even(num):
    if num % 2 == 0 :
        return True
    else:
        return False

In [10]:
list(filter(Even , [2,2,3,4,5,4]))

[2, 2, 4, 4]

In [13]:
def Odd(num):
    if num % 2 != 0 :
        return True
    else:
        return False

In [14]:
list(filter(Odd , [2,2,3,4,5,4]))

[3, 5]

In [ ]:
# restart kernal 

In [3]:
import module 

In [4]:
dir(module)

['Even',
 'Odd',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'add',
 'check']

In [5]:
module.add(12,12)

24

In [7]:
module.Odd(14)

False

In [9]:
list(filter(module.Odd , [2,2,3,4,5,4]))

[3, 5]

In [10]:
list(filter(module.Even , [2,2,3,4,5,4]))

[2, 2, 4, 4]

In [11]:
import module as md

In [13]:
dir(md)

['Even',
 'Odd',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'add',
 'check']

In [12]:
list(filter(md.Even , [2,2,3,4,5,4]))

[2, 2, 4, 4]

In [17]:
from module import Even , Odd

In [18]:
Even(12)

True

In [19]:
Odd(13)

True

In [22]:
from module import *
print(check(13))
print(Even(14))

Odd
True


In [23]:
import random as rn 

In [25]:
# dir(rn)

In [30]:
rn.random()   # 0 >>> 1 

0.4745921360654952

In [39]:
rn.randint(1 , 10) # start >>  included  ,  end >> included

6

In [43]:
for i in range(10):
    print(rn.randint(1 , 10))

8
1
8
7
1
10
7
1
10
9


In [ ]:
rn.randrange(1,10)  # start >>  included  ,  end >> not included

In [45]:
for i in range(10):
    print(rn.randrange(1,10))

4
2
3
8
5
2
3
3
1
6


In [46]:
lst = [1,2,3,4,5,6]

In [47]:
sum(lst)

21

In [48]:
for i in lst :
    print(i * 2 )

2
4
6
8
10
12


In [49]:
import numpy as np 

In [51]:
# dir(np)

In [53]:
lst = [1,2,3,4,5,6]
arr = np.array(lst)

In [54]:
lst * 2 

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [55]:
arr * 2 

array([ 2,  4,  6,  8, 10, 12])

In [56]:
arr + 2 

array([3, 4, 5, 6, 7, 8])

In [57]:
arr ** 2 

array([ 1,  4,  9, 16, 25, 36])

In [58]:
arr

array([1, 2, 3, 4, 5, 6])

In [59]:
lst

[1, 2, 3, 4, 5, 6]

In [60]:
sum(lst) / len(lst)

3.5

In [61]:
arr.mean()

3.5

In [68]:
np.quantile(arr , .50)

3.5

In [69]:
lst = [ [1,2,3] , [2,3,4] , [3,4,5] ]

In [70]:
lst

[[1, 2, 3], [2, 3, 4], [3, 4, 5]]

In [75]:
for i in lst :
    for j in i :
        print(j * 2)

2
4
6
4
6
8
6
8
10


In [71]:
m = np.array(lst)

In [72]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [77]:
w = m * 2 

In [78]:
w

array([[ 2,  4,  6],
       [ 4,  6,  8],
       [ 6,  8, 10]])

In [79]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [82]:
m.shape

3

In [84]:
print("Number of rows is:",  m.shape[0])
print("Number of cols is:",  m.shape[1])

Number of rows is: 3
Number of cols is: 3


In [86]:
t = w * m 

In [87]:
t

array([[ 2,  8, 18],
       [ 8, 18, 32],
       [18, 32, 50]])

In [88]:
t.T

array([[ 2,  8, 18],
       [ 8, 18, 32],
       [18, 32, 50]])

In [89]:
mat = np.array([ [1,2] , [3,4] , [5,6] ])
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
mat.shape

(3, 2)

In [91]:
print("Number of rows is:",  mat.shape[0])
print("Number of cols is:",  mat.shape[1])

Number of rows is: 3
Number of cols is: 2


In [92]:
mat.T

array([[1, 3, 5],
       [2, 4, 6]])

In [95]:
mat.mean()

3.5

In [96]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
np.mean(mat , axis= 0)     # axis= 0 >> col

array([3., 4.])

In [98]:
np.mean(mat , axis= 1)     # axis= 1 >> row

array([1.5, 3.5, 5.5])

In [99]:
mat.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
mat.reshape((6,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [101]:
mat.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

In [108]:
np.arange(10).reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [109]:
arr = np.arange(10)

In [110]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
arr[0]

0

In [112]:
arr[-1]

9

In [113]:
sum(arr)

45

In [114]:
arr.sum()

45

In [115]:
abs(-1)

1

In [116]:
np.abs(-1)

1

In [117]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
# arr[start=0 : stop : step = 1 ]
arr[0 : 4]

array([0, 1, 2, 3])

In [119]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [120]:
lst

[[1, 2, 3], [2, 3, 4], [3, 4, 5]]

In [126]:
lst[0][0]

1

In [124]:
lst[-1]

[3, 4, 5]

In [122]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [127]:
m[0][0]

1

In [125]:
m[-1]

array([3, 4, 5])

In [128]:
# m[rows , cols]
m[0 , 0]

1

In [129]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [130]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
mat[: , :]  # كل الروز وكل الكولومز 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [134]:
mat[: , 0:1]

array([[1],
       [3],
       [5]])

In [139]:
mat[: , 1:2]

array([[2],
       [4],
       [6]])

In [140]:
mat[: , -1:]

array([[2],
       [4],
       [6]])

In [141]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [144]:
mat[1: , :] = 1 

In [145]:
mat

array([[1, 2],
       [1, 1],
       [1, 1]])

In [158]:
np.random.seed(12) # بمعني ان القيم العشوائية هتفضل ثابتة  كل تنفيذة 
data = np.random.randint(10 , 100 , (15 , 5 ))

In [159]:
data

array([[85, 37, 16, 12, 13],
       [77, 86, 58, 32, 59],
       [62, 15, 23, 99, 44],
       [85, 84, 10, 86, 23],
       [92, 99, 45, 72, 45],
       [43, 40, 73, 28, 96],
       [60, 90, 94, 16, 83],
       [55, 40, 42, 37, 69],
       [99, 69, 98, 89, 35],
       [66, 14, 78, 75, 54],
       [47, 85, 78, 63, 85],
       [63, 57, 70, 52, 80],
       [80, 77, 12, 38, 84],
       [68, 69, 94, 64, 65],
       [94, 30, 39, 79, 61]])

In [161]:
data[: , -1:]

array([[13],
       [59],
       [44],
       [23],
       [45],
       [96],
       [83],
       [69],
       [35],
       [54],
       [85],
       [80],
       [84],
       [65],
       [61]])

In [165]:
np.mean(data , axis = 1)   # axis = 1 >> يعبر عن الروزززز

array([32.6, 62.4, 48.6, 57.6, 70.6, 56. , 68.6, 48.6, 78. , 57.4, 71.6,
       64.4, 58.2, 72. , 60.6])

In [167]:
data[0].mean()

32.6

In [176]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3,4,5,6])

In [177]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 3, 4, 5, 6])

In [178]:
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 3, 4, 5, 6])

In [179]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [181]:
arr3 = np.vstack((arr1,arr2))
arr3

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [183]:
np.vstack((arr3,arr1))

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [1, 2, 3, 4]])

In [187]:
try:
    np.hstack((arr3,arr1))
except Exception as e :
    print("Error:", e)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [185]:
arr1

array([1, 2, 3, 4])

In [188]:
arr = np.array([2,3,4,5,6,7,8,9])
print(len(arr))
print(arr.size)

8

In [192]:
mat

array([[1, 2],
       [1, 1],
       [1, 1]])

In [191]:
mat.size

6

In [193]:
len(mat)

3

In [194]:
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [200]:
np.array_split(arr , 2)

[array([2, 3, 4, 5]), array([6, 7, 8, 9])]

In [205]:
np.array_split(arr , 4)

[array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [206]:
mat

array([[1, 2],
       [1, 1],
       [1, 1]])

In [214]:
np.hsplit(mat , 2)

[array([[1],
        [1],
        [1]]),
 array([[2],
        [1],
        [1]])]

In [215]:
arr1

array([1, 2, 3, 4])

In [216]:
arr2

array([3, 4, 5, 6])

In [220]:
arr1 == arr2 

array([False, False, False, False])

In [221]:
arr1 >= 2

array([False,  True,  True,  True])

In [225]:
arr1[arr1 >= 2]

array([2, 3, 4])

In [229]:
np.any(arr1>=3) # اي قيمة من الكونديشن ترو فكدا الناتج هيكون ترو 

True

In [233]:
np.all(arr1>=3)   #  معناها لازم يكون كل القيم الناتجة من الكونديشن تكون ترو عشان الناتج يكون ترو 

False

In [234]:
arr1>=3

array([False, False,  True,  True])

In [237]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [238]:
np.ones((3,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [239]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [242]:
# 10 , 10 
w = np.zeros((10,10))
w

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [244]:
w[0] = 1

In [246]:
w[-1] = 1 

In [248]:
w[: , 0] = 1 

In [250]:
w[: , -1] = 1

In [251]:
w

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [252]:
w = np.zeros((10,10))
w

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [253]:
w[1 : -1 , 1 : -1] = 1 

In [254]:
w

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [255]:
import pandas as pd

In [257]:
# dir(pd)

In [262]:
col_name = "Name Age Address Grade"
df = pd.DataFrame([["A" , 23 , 123 , 90] , ["B" , 24 , 234 , 70] , ["C" , 22 , 134 , 85]],
            columns=col_name.split())    # ["Name" , "Age" , "Address" , "Grade"]

In [264]:
type(df)

pandas.core.frame.DataFrame

In [265]:
df

Name  Age  Address  Grade
0    A   23      123     90
1    B   24      234     70
2    C   22      134     85

In [267]:
type(df["Name"])

pandas.core.series.Series

In [272]:
df["Name"].str.lower()

0    a
1    b
2    c
Name: Name, dtype: object

In [273]:
df["Name"].apply(str.lower)

0    a
1    b
2    c
Name: Name, dtype: object

In [274]:
df

Name  Age  Address  Grade
0    A   23      123     90
1    B   24      234     70
2    C   22      134     85

In [276]:
df["Age"].sum()

69

In [277]:
df["Age"].mean()

23.0

In [278]:
df["Age"].median()

23.0

In [282]:
df[["Name" , "Age"]]

Name  Age
0    A   23
1    B   24
2    C   22

In [283]:
df["Age"] == 23

0     True
1    False
2    False
Name: Age, dtype: bool

In [284]:
df[df["Age"] == 23]

Name  Age  Address  Grade
0    A   23      123     90

In [288]:
df["Age"] == 24

0    False
1     True
2    False
Name: Age, dtype: bool

In [293]:
df["Name"] == "C"

0    False
1    False
2     True
Name: Name, dtype: bool

In [294]:
df[df["Name"] == "C"]

Name  Age  Address  Grade
2    C   22      134     85

In [297]:
df.query("Name == 'C' and Address == 123 ")

Empty DataFrame
Columns: [Name, Age, Address, Grade]
Index: []

In [298]:
df.query("Name == 'C' or Address == 123 ")

Name  Age  Address  Grade
0    A   23      123     90
2    C   22      134     85

In [299]:
df

Name  Age  Address  Grade
0    A   23      123     90
1    B   24      234     70
2    C   22      134     85

In [303]:
def check(num):
    if num % 2 == 0 :
        return "Even"
    else:
        return "Odd"
    
df["odd_even"] = df["Grade"].apply(check)

In [304]:
df

Name  Age  Address  Grade odd_even
0    A   23      123     90     Even
1    B   24      234     70     Even
2    C   22      134     85      Odd

In [309]:
df["replace"] = df["odd_even"].replace({"Even" : 0 , "Odd" : 1})

In [310]:
df

Name  Age  Address  Grade odd_even  replace
0    A   23      123     90     Even        0
1    B   24      234     70     Even        0
2    C   22      134     85      Odd        1

In [311]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Name      3 non-null      object
 1   Age       3 non-null      int64 
 2   Address   3 non-null      int64 
 3   Grade     3 non-null      int64 
 4   odd_even  3 non-null      object
 5   replace   3 non-null      int64 
dtypes: int64(4), object(2)
memory usage: 272.0+ bytes


In [314]:
df.describe().T

count        mean        std    min    25%    50%    75%    max
Age        3.0   23.000000   1.000000   22.0   22.5   23.0   23.5   24.0
Address    3.0  163.666667  61.158265  123.0  128.5  134.0  184.0  234.0
Grade      3.0   81.666667  10.408330   70.0   77.5   85.0   87.5   90.0
replace    3.0    0.333333   0.577350    0.0    0.0    0.0    0.5    1.0

In [315]:
df.describe(include="object").T

count unique   top freq
Name         3      3     A    1
odd_even     3      2  Even    2

In [316]:
df

Name  Age  Address  Grade odd_even  replace
0    A   23      123     90     Even        0
1    B   24      234     70     Even        0
2    C   22      134     85      Odd        1

In [317]:
df.columns

Index(['Name', 'Age', 'Address', 'Grade', 'odd_even', 'replace'], dtype='object')

In [318]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [320]:
df.to_csv("df_result" , index=False)

In [322]:
df2 = pd.read_csv("CarPrice_Assignment.csv")

In [327]:
df2.head(3)  # 5 rowsssss

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   

       carbody drivewheel enginelocation  wheelbase  ...  fuelsystem  \
0  convertible        rwd          front       88.6  ...        mpfi   
1  convertible        rwd          front       88.6  ...        mpfi   
2    hatchback        rwd          front       94.5  ...        mpfi   

   boreratio  stroke  compressionratio horsepower peakrpm  citympg highwaympg  \
0       3.47    2.68               9.0        111    5000       21         27   
1       3.47    2.68               9.0        111    5000       21         27   
2       2.68    3.47               9.0        154    5000       19         26   

     price  highwaympg.1  
0  13495.0            27  
1  16500.0            27  
2  16500.0            26  

[3 rows x 27 columns]