In [3]:
import numpy as np

In [8]:
x = np.array([1,2,3,4,5,6,7,8,9])
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
mean  = sum(x) / len(x)
mean

5.0

In [9]:
np.mean(x)

5.0

In [11]:
m = np.array([[1,2,3] , [2,3,4] , [4,5,6]])
m

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [13]:
round(np.mean(m) , 2 )

3.33

In [18]:
np.mean(m , axis = 0)   #axis = 0 >> col 

array([2.33333333, 3.33333333, 4.33333333])

In [19]:
(1 + 2 + 4 ) / 3

2.3333333333333335

In [20]:
(3 + 4 + 6 ) / 3

4.333333333333333

In [21]:
np.mean(m , axis = 1)   #axis = 1 >> row

array([2., 3., 5.])

In [23]:
np.quantile(x , .50)   # median

5.0

In [24]:
np.median(x)

5.0

In [30]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [26]:
np.median(m)   #    1 , 2 ,2 , 3 , 4 , 4, 5, 6 

3.0

In [28]:
np.median(m , axis = 0 )

array([2., 3., 4.])

In [29]:
np.median(m , axis = 1 )

array([2., 3., 5.])

In [31]:
x = np.array([5,5,5,5,5,5,5])
np.mean(x)

5.0

In [32]:
np.var(x)

0.0

In [33]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [34]:
np.var(m)

2.2222222222222223

In [35]:
np.var(m , axis = 0)

array([1.55555556, 1.55555556, 1.55555556])

In [36]:
np.var(m , axis = 1)

array([0.66666667, 0.66666667, 0.66666667])

In [37]:
np.std(x)

0.0

In [38]:
y = np.array([1,2,3,4,5,6,7,8,9])
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.std(y)

2.581988897471611

In [55]:
x = np.array([9,8,7,6,5,4,3,2,1])
y = np.array([1,2,3,4,5,6,7,8,9])

In [56]:
np.cov(x,y)

array([[ 7.5, -7.5],
       [-7.5,  7.5]])

In [57]:
np.cov(x,y)[0 , 1]

-7.5

In [58]:
np.corrcoef(x,y)[1 , 0]

-1.0

In [59]:
# q1 = np.quantile(col , .25)
# q3 = np.quantile(col , .75)
# IQR = q3 - q1 
# min = q1 - (1.5 * IQR)
# max = q3 + (1.5 * IQR)
# outliers min ............... max  outliers 